import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";

import Provider from "./provider";
import "./globals.css";
import Toaster from "@/components/ui/toaster";
import ThemeProvider from "./theme-provider";

export const metadata: Metadata = {
    title: "AI PicMotion Lab",
    description: "Generated by SonDev",
    icons: {
        icon: "/logo.svg",
    }
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body cz-shortcut-listen="true">
                <ClerkProvider>
                    <ThemeProvider>
                        <Provider>{children}</Provider>
                        <Toaster />
                    </ThemeProvider>
                </ClerkProvider>
            </body>
        </html>
    );
}
